services:
  mongo:
    image: mongo:7
    container_name: velora-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: velora-server
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: velora-client
    restart: unless-stopped
    ports:
      - "5172:5172"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    command: npm run dev -- --host 0.0.0.0

volumes:
  mongo_data:
